#!/bin/sh

# Non contigious allocation

PROGRAM_NAME="../file_system"
FILE_SYSTEM_BINARY_NAME="../file_system.bin"
$PROGRAM_NAME init $FILE_SYSTEM_BINARY_NAME

$PROGRAM_NAME copy_to_disk $FILE_SYSTEM_BINARY_NAME test_file_2.txt
$PROGRAM_NAME copy_to_disk $FILE_SYSTEM_BINARY_NAME test_file_4.txt

$PROGRAM_NAME list $FILE_SYSTEM_BINARY_NAME
$PROGRAM_NAME show_usage $FILE_SYSTEM_BINARY_NAME

$PROGRAM_NAME delete $FILE_SYSTEM_BINARY_NAME test_file_2.txt

$PROGRAM_NAME list $FILE_SYSTEM_BINARY_NAME
$PROGRAM_NAME show_usage $FILE_SYSTEM_BINARY_NAME

$PROGRAM_NAME copy_to_disk $FILE_SYSTEM_BINARY_NAME test_file_3.txt

$PROGRAM_NAME list $FILE_SYSTEM_BINARY_NAME
$PROGRAM_NAME show_usage $FILE_SYSTEM_BINARY_NAME

$PROGRAM_NAME copy_from_disk $FILE_SYSTEM_BINARY_NAME test_file_3.txt restored_test_file_3
$PROGRAM_NAME copy_from_disk $FILE_SYSTEM_BINARY_NAME test_file_4.txt restored_test_file_4

$PROGRAM_NAME delete $FILE_SYSTEM_BINARY_NAME test_file_3.txt
$PROGRAM_NAME delete $FILE_SYSTEM_BINARY_NAME test_file_4.txt

$PROGRAM_NAME list $FILE_SYSTEM_BINARY_NAME
$PROGRAM_NAME show_usage $FILE_SYSTEM_BINARY_NAME